In [1]:
import pandas as pd
import glob
import os

# Define the directory where your JSON files are located
data_dir = "/usr/xtmp/eyc14/project/data"

# Use glob to find all JSON files in the directory
json_files = glob.glob(os.path.join(data_dir, "*.json"))

# Read each JSON file and store in a list of DataFrames
dfs = [pd.read_json(f, lines=True) for f in json_files]

# Concatenate all DataFrames into one
df = pd.concat(dfs, ignore_index=True)

# Print or work with the combined DataFrame
df.head()

,publication_number,title_localized,abstract_localized,claims_localized,description_localized,uspc,ipc,fi,fterm,citation,grant_year
0,US-8558326-B2,[{'text': 'Semiconductor devices having nanoch...,[{'text': 'Semiconductor devices having integr...,[{'text': 'What is claimed is: ...,[{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...,"[{'code': '257/414.', 'inventive': False, 'fir...","[{'code': 'H01L27/14', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-7001792-B2', 'appl...",2013
1,US-8896003-B2,[{'text': 'Separate optical device for directi...,[{'text': 'Embodiments of the present inventio...,[{'text': 'What is claimed is: 1...,[{'text': 'RELATED APPLICATIONS This app...,"[{'code': '257/95.', 'inventive': False, 'firs...","[{'code': 'G02B19/00', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-1670837-A', 'appli...",2014
2,US-9153520-B2,[{'text': 'Stacked semiconductor die assemblie...,[{'text': 'Stacked semiconductor die assemblie...,[{'text': 'We claim: 1. A semico...,[{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...,[],"[{'code': 'H01L25/18', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-5536907-A', 'appli...",2015
3,US-8869863-B2,[{'text': 'Delamination apparatus and inline t...,[{'text': 'A delamination apparatus includes a...,[{'text': 'What is claimed is: 1...,[{'text': 'CLAIM OF PRIORITY This applic...,"[{'code': '156/760.', 'inventive': False, 'fir...","[{'code': 'B32B38/10', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-5169474-A', 'appli...",2014
4,US-8148783-B2,"[{'text': 'Semiconductor device', 'language': ...",[{'text': 'Semiconductor device including semi...,[{'text': 'What is claimed is: 1...,[{'text': 'BACKGROUND OF THE INVENTION 1...,"[{'code': '257/367.', 'inventive': False, 'fir...","[{'code': 'H01L31/062', 'inventive': True, 'fi...",[],[],"[{'publication_number': 'US-5455439-A', 'appli...",2012

In [2]:
print(df.shape)

(135976, 11)

In [3]:
df.to_json('patents.json', records=)

In [2]:
import pandas as pd
import glob
import os
df = pd.read_json('patents.json')

KeyboardInterrupt:

In [ ]:
label = pd.read_csv('/usr/xtmp/eyc14/project/semiconductor_patents_2010_2015_5yr_cit.csv')
label.head()

  publication_number  grant_yr  cit_5yr_window
0      US-7781257-B2      2010               1
1      US-7671428-B2      2010               1
2      US-7807038-B2      2010               1
3      US-7745315-B1      2010               1
4      US-7655270-B2      2010               1

In [ ]:
df.head()

,publication_number,title_localized,abstract_localized,claims_localized,description_localized,uspc,ipc,fi,fterm,citation,grant_year
0,US-8558326-B2,[{'text': 'Semiconductor devices having nanoch...,[{'text': 'Semiconductor devices having integr...,[{'text': 'What is claimed is: ...,[{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...,"[{'code': '257/414.', 'inventive': False, 'fir...","[{'code': 'H01L27/14', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-7001792-B2', 'appl...",2013
1,US-8896003-B2,[{'text': 'Separate optical device for directi...,[{'text': 'Embodiments of the present inventio...,[{'text': 'What is claimed is: 1...,[{'text': 'RELATED APPLICATIONS This app...,"[{'code': '257/95.', 'inventive': False, 'firs...","[{'code': 'G02B19/00', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-1670837-A', 'appli...",2014
2,US-9153520-B2,[{'text': 'Stacked semiconductor die assemblie...,[{'text': 'Stacked semiconductor die assemblie...,[{'text': 'We claim: 1. A semico...,[{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...,[],"[{'code': 'H01L25/18', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-5536907-A', 'appli...",2015
3,US-8869863-B2,[{'text': 'Delamination apparatus and inline t...,[{'text': 'A delamination apparatus includes a...,[{'text': 'What is claimed is: 1...,[{'text': 'CLAIM OF PRIORITY This applic...,"[{'code': '156/760.', 'inventive': False, 'fir...","[{'code': 'B32B38/10', 'inventive': True, 'fir...",[],[],"[{'publication_number': 'US-5169474-A', 'appli...",2014
4,US-8148783-B2,"[{'text': 'Semiconductor device', 'language': ...",[{'text': 'Semiconductor device including semi...,[{'text': 'What is claimed is: 1...,[{'text': 'BACKGROUND OF THE INVENTION 1...,"[{'code': '257/367.', 'inventive': False, 'fir...","[{'code': 'H01L31/062', 'inventive': True, 'fi...",[],[],"[{'publication_number': 'US-5455439-A', 'appli...",2012

In [ ]:
# Keep only the desired columns
columns_text = ["publication_number", "title_localized","claims_localized", "abstract_localized", "description_localized"]
data_text = df[columns_text]

# Drop rows with any nulls in those columns
data_text  = data_text.dropna(subset=columns_text)

# Optional: reset index if needed
data_text = data_text .reset_index(drop=True)
merged_df = pd.merge(
    data_text,
    label[["publication_number", "cit_5yr_window"]],
    on="publication_number",
    how="inner"  # or 'left' if you want to keep all rows from df
)
merged_df.reset_index(drop=True)



print(merged_df.head())

  publication_number                                    title_localized  \
0      US-8558326-B2  [{'text': 'Semiconductor devices having nanoch...
1      US-8896003-B2  [{'text': 'Separate optical device for directi...
2      US-9153520-B2  [{'text': 'Stacked semiconductor die assemblie...
3      US-8869863-B2  [{'text': 'Delamination apparatus and inline t...
4      US-8148783-B2  [{'text': 'Semiconductor device', 'language': ...

                                    claims_localized  \
0  [{'text': 'What is claimed is:

       ...
1  [{'text': 'What is claimed is:

       1...
2  [{'text': 'We claim:

       1. A semico...
3  [{'text': 'What is claimed is:

       1...
4  [{'text': 'What is claimed is:

       1...

                                  abstract_localized  \
0  [{'text': 'Semiconductor devices having integr...
1  [{'text': 'Embodiments of the present inventio...
2  [{'text': 'Stacked semiconductor die assemblie...
3  [{'text': 'A delamination apparatus includes a...
4  [{'text': 'Semiconductor device including semi...

                               description_localized
0  [{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...
1  [{'text': 'RELATED APPLICATIONS
     This app...
2  [{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...
3  [{'text': 'CLAIM OF PRIORITY
     This applic...
4  [{'text': 'BACKGROUND OF THE INVENTION
     1...
Index(['publication_number', 'title_localized', 'claims_localized',
       'abstract_localized', 'description_localized'],
      dtype='object')
  publication_number                                    title_localized  \
0      US-8558326-B2  [{'text': 'Semiconductor devices having nanoch...
1      US-8896003-B2  [{'text': 'Separate optical device for directi...
2      US-9153520-B2  [{'text': 'Stacked semiconductor die assemblie...
3      US-8869863-B2  [{'text': 'Delamination apparatus and inline t...
4      US-8148783-B2  [{'text': 'Semiconductor device', 'language': ...

                                    claims_localized  \
0  [{'text': 'What is claimed is:

       ...
1  [{'text': 'What is claimed is:

       1...
2  [{'text': 'We claim:

       1. A semico...
3  [{'text': 'What is claimed is:

       1...
4  [{'text': 'What is claimed is:

       1...

                                  abstract_localized  \
0  [{'text': 'Semiconductor devices having integr...
1  [{'text': 'Embodiments of the present inventio...
2  [{'text': 'Stacked semiconductor die assemblie...
3  [{'text': 'A delamination apparatus includes a...
4  [{'text': 'Semiconductor device including semi...

                               description_localized  cit_5yr_window
0  [{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...               1
1  [{'text': 'RELATED APPLICATIONS
     This app...               1
2  [{'text': 'CROSS-REFERENCE TO RELATED APPLICAT...               9
3  [{'text': 'CLAIM OF PRIORITY
     This applic...               2
4  [{'text': 'BACKGROUND OF THE INVENTION
     1...               3

In [4]:
for col in ["claims_localized", "abstract_localized", "description_localized", "title_localized"]:
    merged_df[col] = merged_df[col].apply(
        lambda x: x[0].get("text", "").replace("\n", " ") 
        if isinstance(x, list) and len(x) > 0 and isinstance(x[0], dict) else None
    )
print(data_text.shape)
merged_df["publication_number"] = merged_df["publication_number"].str.replace("-", "", regex=False)

merged_df.head()

(135976, 5)

,publication_number,title_localized,claims_localized,abstract_localized,description_localized,cit_5yr_window
0,US8558326B2,Semiconductor devices having nanochannels conf...,What is claimed is: 1. A semico...,Semiconductor devices having integrated nanoch...,CROSS-REFERENCE TO RELATED APPLICATION T...,1
1,US8896003B2,Separate optical device for directing light fr...,What is claimed is: 1. A separat...,Embodiments of the present invention provide s...,RELATED APPLICATIONS This application is...,1
2,US9153520B2,Stacked semiconductor die assemblies with mult...,We claim: 1. A semiconductor die...,Stacked semiconductor die assemblies with mult...,CROSS-REFERENCE TO RELATED APPLICATIONS ...,9
3,US8869863B2,Delamination apparatus and inline thermal imag...,What is claimed is: 1. A delamin...,"A delamination apparatus includes a stage, a f...",CLAIM OF PRIORITY This application makes...,2
4,US8148783B2,Semiconductor device,What is claimed is: 1. A semicon...,Semiconductor device including semiconductor l...,BACKGROUND OF THE INVENTION 1. Field of ...,3

In [5]:
merged_df.dropna(inplace=True)
merged_df.reset_index(drop=True)
print(merged_df.shape)

(81731, 6)

In [9]:
merged_df.to_pickle('patent_text.pkl')

In [1]:
import pandas as pd
merged_df = pd.read_pickle('/usr/xtmp/eyc14/project/patent_text.pkl')

In [2]:
print(merged_df.head())

  publication_number                                    title_localized  \
0        US8558326B2  Semiconductor devices having nanochannels conf...
1        US8896003B2  Separate optical device for directing light fr...
2        US9153520B2  Stacked semiconductor die assemblies with mult...
3        US8869863B2  Delamination apparatus and inline thermal imag...
4        US8148783B2                               Semiconductor device

                                    claims_localized  \
0  What is claimed is:                1. A semico...
1  What is claimed is:               1. A separat...
2  We claim:               1. A semiconductor die...
3  What is claimed is:               1. A delamin...
4  What is claimed is:               1. A semicon...

                                  abstract_localized  \
0  Semiconductor devices having integrated nanoch...
1  Embodiments of the present invention provide s...
2  Stacked semiconductor die assemblies with mult...
3  A delamination apparatus includes a stage, a f...
4  Semiconductor device including semiconductor l...

                               description_localized  cit_5yr_window
0  CROSS-REFERENCE TO RELATED APPLICATION       T...               1
1  RELATED APPLICATIONS       This application is...               1
2  CROSS-REFERENCE TO RELATED APPLICATIONS       ...               9
3  CLAIM OF PRIORITY       This application makes...               2
4  BACKGROUND OF THE INVENTION       1. Field of ...               3

In [3]:
import torch
from torch.utils.data import Dataset, DataLoader
from torch.utils.data import random_split
from transformers import AutoTokenizer
import os
from PIL import Image, UnidentifiedImageError
import torchvision.transforms as T
import torchvision.transforms.functional as F

class ResizePadToSquare:
    def __init__(self, target_size=224, fill=255):
        self.target_size = target_size
        self.fill = fill

    def __call__(self, image: Image.Image):
        # Convert to grayscale if not L or RGB
        if image.mode not in ['L', 'RGB']:
            image = image.convert('L')

        w, h = image.size
        scale = self.target_size / max(w, h)
        new_w, new_h = int(w * scale), int(h * scale)
        image = F.resize(image, (new_h, new_w))

        # Padding to square
        if image.mode == 'L':
            new_image = Image.new("L", (self.target_size, self.target_size), self.fill)
        else:
            new_image = Image.new("RGB", (self.target_size, self.target_size), (self.fill,) * 3)

        paste_x = (self.target_size - new_w) // 2
        paste_y = (self.target_size - new_h) // 2
        new_image.paste(image, (paste_x, paste_y))

        # Convert grayscale to RGB if needed
        if new_image.mode == 'L':
            new_image = new_image.convert('RGB')

        return new_image


transform = T.Compose([
    ResizePadToSquare(target_size=224),  # your custom transform
    T.ToTensor(),                        # [0, 255] to [0.0, 1.0]
    T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])  # normalize to [-1, 1]
])

class PatentDataset(Dataset):
    def __init__(self, df, tokenizer, image_dir, transform, max_words=150, batch_size=16, max_length=512, label_column="cit_5yr_window"):
        self.df = df
        self.tokenizer = tokenizer
        self.max_words = max_words
        self.batch_size = batch_size
        self.max_length = max_length
        self.label_column = label_column

        # Group all images by patent ID
        self.transform = transform
        self.patent_to_images = {}
        for filename in os.listdir(image_dir):
            if filename.endswith('.png'):
                patent_id = filename.split('_')[0]
                path = os.path.join(image_dir, filename)
                self.patent_to_images.setdefault(patent_id, []).append(path)
        
        # Patent ID list is the dataset index
        self.patent_ids = list(self.patent_to_images.keys())
        self.valid_indices = self._find_valid_indices()

    def chunk_text(self, text):
        words = text.split()
        return [' '.join(words[i:i + self.max_words]) for i in range(0, len(words), self.max_words)]

    def tokenize_chunks(self, text):
        chunks = self.chunk_text(text)
        # Tokenize all chunks at once
        inputs = self.tokenizer(chunks, padding='max_length', truncation=True, 
                              return_tensors='pt', max_length=self.max_length)
        return {
            "input_ids": inputs["input_ids"],
            "attention_mask": inputs["attention_mask"]
        }
        
    def _find_valid_indices(self):
        valid_indices = []
        for idx in range(len(self.df)):
            row = self.df.iloc[idx]
            patent_id = row["publication_number"]
            if (patent_id in self.patent_to_images and 
                len(self.patent_to_images[patent_id]) > 0):
                valid_indices.append(idx)
        return valid_indices
    
    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        row = self.df.iloc[actual_idx]
        patent_id = row["publication_number"]
        image_paths = self.patent_to_images[patent_id]

        images = []
        for path in sorted(image_paths):  # sort for consistency
            try:
                img = Image.open(path).convert("RGB")  # Always force RGB
            except UnidentifiedImageError:
                continue
            if self.transform:
                img = self.transform(img)
            images.append(img)

        # Return stacked images [num_images, 3, H, W] and the patent ID
        image_tensor = torch.stack(images)
        return {
            "title": self.tokenize_chunks(row["title_localized"]),
            "abstract": self.tokenize_chunks(row["abstract_localized"]),
            "claims": self.tokenize_chunks(row["claims_localized"]),
            "description": self.tokenize_chunks(row["description_localized"]),
            "images": image_tensor,
            "label": torch.tensor(row[self.label_column], dtype=torch.float)
        }


# Example Usage
model_name = 'AI-Growth-Lab/PatentSBERTa'


# Example Usage
tokenizer = AutoTokenizer.from_pretrained(model_name)
dataset = PatentDataset(merged_df, tokenizer, 'data/patent_image/2010',transform, batch_size=16)
# Set your split proportions
train_ratio = 0.8
val_ratio = 0.1
test_ratio = 0.1

# Calculate lengths
dataset_size = len(dataset)
train_size = int(train_ratio * dataset_size)
val_size = int(val_ratio * dataset_size)
test_size = dataset_size - train_size - val_size  # ensure total matches

# Split the dataset
train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])

/usr/xtmp/eyc14/project/dlhw/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [53]:
#

<__main__.PatentDataset object at 0x7f901d262560>

In [6]:
import torch
import torch.nn as nn
from transformers import ViTModel

class WeightedImagePooling(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.attn = nn.Linear(input_dim, 1)

    def forward(self, image_embeddings):  # [N, D]
        weights = self.attn(image_embeddings)  # [N, 1]
        weights = torch.softmax(weights.squeeze(-1), dim=0)  # [N]
        pooled = (image_embeddings * weights.unsqueeze(-1)).sum(dim=0)  # [D]
        return pooled

class PatentImageEncoder(nn.Module):
    def __init__(self, pooling='mean'):
        super().__init__()

        # Load pretrained ViT
        self.vit = ViTModel.from_pretrained('google/vit-base-patch16-224-in21k')
        self.hidden_size = self.vit.config.hidden_size  # e.g. 768

        # Choose pooling strategy
        if pooling == 'mean':
            self.pooling = self.mean_pooling
        elif pooling == 'weighted':
            self.pooling = WeightedImagePooling(self.hidden_size)
        else:
            raise ValueError("pooling must be 'mean' or 'weighted'")

    def mean_pooling(self, image_embeddings):  # [N, D]
        return image_embeddings.mean(dim=0)

    def forward(self, image_batch):  # image_batch: [N, 3, 224, 224] (N images for one patent)
        outputs = self.vit(pixel_values=image_batch)
        cls_embeddings = outputs.last_hidden_state[:, 0, :]  # [N, D]
        pooled = self.pooling(cls_embeddings)  # [D]
        return pooled


encoder = PatentImageEncoder()
encoder.eval()
features = []

with torch.no_grad():
    for batch_images, batch_ids in tqdm(loader):
        batch_features = []
        for image_tensor in batch_images:
            feature = encoder(image_tensor)  # [768]
            batch_features.append(feature)

        batch_features = torch.stack(batch_features)  # [batch_size, 768]
        print("Batch patent feature shape:", batch_features.shape)
        break

NameError: name 'tqdm' is not defined

In [4]:
def collate_fn(batch):
    # Extract all components from the batch
    titles = [item["title"] for item in batch]  # List of tokenized title chunks
    abstracts = [item["abstract"] for item in batch]  # List of tokenized abstract chunks
    claims = [item["claims"] for item in batch]  # List of tokenized claims chunks
    images = [item["images"] for item in batch]  # List of image tensors
    labels = [item["label"] for item in batch]  # List of label tensors

    # Handle text fields (title, abstract, claims)
    def process_text_field(field_data):
        # field_data is a list where each item is a dict with "input_ids" and "attention_mask"
        # Flatten all chunks across all samples
        all_input_ids = []
        all_attention_masks = []
        chunk_counts = []  # Track number of chunks per sample
        
        for sample in field_data:
            chunk_counts.append(len(sample["input_ids"]))
            all_input_ids.extend(sample["input_ids"])
            all_attention_masks.extend(sample["attention_mask"])
        
        # Stack all chunks
        input_ids = torch.stack(all_input_ids)
        attention_mask = torch.stack(all_attention_masks)
        
        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "chunk_counts": torch.tensor(chunk_counts, dtype=torch.long)
        }

    processed_titles = process_text_field(titles)
    processed_abstracts = process_text_field(abstracts)
    processed_claims = process_text_field(claims)

    # Handle images to match text processing style
    def process_images(image_data):
        all_images = []
        image_counts = []  # Track number of images per sample
        
        for sample in image_data:
            num_images = sample.size(0)
            image_counts.append(num_images)
            if num_images > 0:
                all_images.append(sample)
        
        # Stack all images if there are any, otherwise return empty tensor
        if len(all_images) > 0:
            images_tensor = torch.cat(all_images, dim=0)
        else:
            # Create empty tensor with correct dimensions
            images_tensor = torch.empty(0, *image_data[0].shape[1:])
        
        return {
            "images": images_tensor,
            "image_counts": torch.tensor(image_counts, dtype=torch.long)
        }

    processed_images = process_images(images)

    return {
        "title": processed_titles,
        "abstract": processed_abstracts,
        "claims": processed_claims,
        "images": processed_images,
        "label": torch.stack(labels)
    }

In [6]:
import torch
import torch.nn as nn
from transformers import AutoModel
from tqdm import tqdm

def set_encoder_trainable(model, trainable):
    """Sets all encoders to be trainable or frozen."""
    for encoder in [model.encoder_title, model.encoder_abstract, model.encoder_claims]:
        for param in encoder.parameters():
            param.requires_grad = trainable
class AttentionPooling(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        self.attention = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 1)
        )
    def forward(self, token_embeddings, attention_mask):
        # attention_mask: [batch_size, seq_len]
        scores = self.attention(token_embeddings).squeeze(-1)  # [batch_size, seq_len]
        scores = scores.masked_fill(attention_mask == 0, -1e9)  # mask padded tokens
        weights = torch.softmax(scores, dim=1).unsqueeze(-1)    # [batch_size, seq_len, 1]
        return torch.sum(token_embeddings * weights, dim=1)     # weighted sum over tokens

class PatentEmbeddingModel(nn.Module):
    def __init__(self, device, hidden=128, model_name="bert-base-uncased", num_outputs=1, freeze_encoder=True):
        super().__init__()
        self.device = device
        self.hidden = hidden
        
        # Separate encoders for each input
        self.encoder_title = AutoModel.from_pretrained(model_name)
        self.encoder_abstract = AutoModel.from_pretrained(model_name)
        self.encoder_claims = AutoModel.from_pretrained(model_name)
        # self.encoder_description = AutoModel.from_pretrained(model_name)

        self.hidden_size = self.encoder_title.config.hidden_size

        # Projection layers for each text component
        self.proj_title = nn.Linear(self.hidden_size, self.hidden)
        self.proj_abstract = nn.Linear(self.hidden_size, self.hidden)
        self.proj_claims = nn.Linear(self.hidden_size, self.hidden)
        self.proj_description = nn.Linear(self.hidden_size, self.hidden)
        self.pooling = AttentionPooling(self.hidden_size)
        # Final regression layer
        self.regressor = nn.Linear(self.hidden * 3, num_outputs)
        # self.regressor = nn.Linear(self.hidden * 4, num_outputs)


        # Set encoder freeze state
        set_encoder_trainable(self, not freeze_encoder)

    def mean_pooling(self, model_output, attention_mask):
        token_embeddings = model_output.last_hidden_state
        mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.shape)
        sum_embeddings = torch.sum(token_embeddings * mask_expanded, dim=1)
        sum_mask = torch.clamp(mask_expanded.sum(dim=1), min=1e-9)
        return sum_embeddings / sum_mask

    def get_embedding(self, encoder, batched_inputs):
            
        input_ids = batched_inputs["input_ids"].to(self.device)
        attention_mask = batched_inputs["attention_mask"].to(self.device)
        chunk_counts = batched_inputs["chunk_counts"].to(self.device)
        
        # Get embeddings for all chunks
        with torch.no_grad():
            outputs = encoder(input_ids=input_ids, attention_mask=attention_mask)
        
        # Pool embeddings for each chunk (using your specified pooling method)
        chunk_embeddings = self.pooling(outputs.last_hidden_state, attention_mask)
        
        # Split chunk embeddings back to original samples using chunk_counts
        embeddings_split = torch.split(chunk_embeddings, chunk_counts.tolist())
        sample_embeddings = torch.stack([emb.mean(dim=0) for emb in embeddings_split])
        return sample_embeddings

    def forward(self, title, abstract, claims):
        # description_emb = self.proj_description(self.get_embedding(self.encoder_description, description))
        title_emb = self.proj_title(self.get_embedding(self.encoder_title, title))
        abstract_emb = self.proj_abstract(self.get_embedding(self.encoder_abstract, abstract))
        claims_emb = self.proj_claims(self.get_embedding(self.encoder_claims, claims))
        # description_emb = self.proj_description(self.get_embedding(self.encoder_description, description))
        # combined_emb = torch.cat([title_emb, abstract_emb, claims_emb, description_emb], dim=1)
        combined_emb = torch.cat([title_emb, abstract_emb, claims_emb], dim=1)
        return self.regressor(combined_emb)

In [13]:
# from torch.utils.data import DataLoader

# def collate_fn(batch):
#     # Custom collate function to handle our data structure
#     return {
#         "title": [item["title"] for item in batch],
#         "abstract": [item["abstract"] for item in batch],
#         "claims": [item["claims"] for item in batch],
#         "images": [item["images"] for item in batch],
#         "label": torch.stack([item["label"] for item in batch])
        
#     }

# dataloader = DataLoader(dataset, batch_size=32, shuffle=True, collate_fn=collate_fn, 
#     pin_memory=True)

In [7]:
import torch
import torch.nn as nn
from tqdm import tqdm
import os

def train_model(model, device, train_loader, val_loader, epochs=3, lr=1e-4, fine_tune=False, save_path="best_model.pt"):
    # Adjust encoder trainability before training
    set_encoder_trainable(model, fine_tune)

    if fine_tune:
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    else:
        encoder_params = list(model.encoder_title.parameters()) + \
                         list(model.encoder_abstract.parameters()) + \
                         list(model.encoder_claims.parameters())
        encoder_param_ids = set(id(p) for p in encoder_params)
        non_encoder_params = [p for p in model.parameters() if id(p) not in encoder_param_ids]
        optimizer = torch.optim.AdamW(non_encoder_params, lr=lr)

    criterion = nn.MSELoss()
    model.train()
    best_val_loss = float("inf")

    for epoch in range(epochs):
        total_loss = 0
        model.train()
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [Training]", leave=False)

        for batch in progress_bar:
            optimizer.zero_grad()
            outputs = model(
                title=batch["title"],
                abstract=batch["abstract"],
                claims=batch["claims"]
            ).squeeze()
            loss = criterion(outputs, batch["label"].to(device))
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            progress_bar.set_postfix(train_loss=loss.item())

        train_loss = total_loss / len(train_loader)

        # Evaluate on validation set
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for batch in val_loader:
                outputs = model(
                    title=batch["title"],
                    abstract=batch["abstract"],
                    claims=batch["claims"]
                ).squeeze()
                loss = criterion(outputs, batch["label"].to(device))
                val_loss += loss.item()

        val_loss /= len(val_loader)
        print(f"Epoch {epoch+1}, Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")

        # Save model if validation improves
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), save_path)
            print(f"✅ New best model saved at epoch {epoch+1} with val loss {val_loss:.4f}")

In [10]:
from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, collate_fn=collate_fn)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, collate_fn=collate_fn)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PatentEmbeddingModel(device=device, model_name=model_name, freeze_encoder=True).to(device)
# Training with frozen encoder
train_model(model, device, train_loader, val_loader, epochs=3, fine_tune=False, save_path="/usr/xtmp/eyc14/project/frozen_encoder_best.pt")

# Fine-tuning with encoder unfrozen
train_model(model, device, train_loader, val_loader, epochs=3, fine_tune=True, save_path="/usr/xtmp/eyc14/project/fine_tuned_best.pt")

KeyboardInterrupt:

In [7]:
def train_model(model, device, dataloader, epochs=3, lr=1e-4, fine_tune=False):
    # Adjust encoder trainability before training
    set_encoder_trainable(model, fine_tune)

    if fine_tune:
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    else:
        encoder_params = list(model.encoder_title.parameters()) + \
                         list(model.encoder_abstract.parameters()) + \
                         list(model.encoder_claims.parameters())
                        #  list(model.encoder_description.parameters())
        encoder_param_ids = set(id(p) for p in encoder_params)
        non_encoder_params = [p for p in model.parameters() if id(p) not in encoder_param_ids]
        optimizer = torch.optim.AdamW(non_encoder_params, lr=lr)
    
    criterion = nn.MSELoss()
    model.train()

    for epoch in range(epochs):
        total_loss = 0
        progress_bar = tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}", leave=False)
        for batch in progress_bar:
            optimizer.zero_grad()
            outputs = model(
                title=batch["title"],
                abstract=batch["abstract"],
                claims=batch["claims"]).squeeze()
            loss = criterion(outputs, batch["label"].to(device))
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            progress_bar.set_postfix(loss=loss.item())
        epoch_loss = total_loss / len(dataloader)
        print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}")

# Model setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PatentEmbeddingModel(device=device, model_name=model_name, freeze_encoder=True).to(device)

# Initial training with frozen encoder
train_model(model, device, dataloader, epochs=3, fine_tune=False)

# Fine-tuning with encoder unfrozen
train_model(model, device, dataloader, epochs=3, fine_tune=True)

Epoch 1/3:   0%|          | 1/409 [00:11<1:15:15, 11.07s/it, loss=277]

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

Epoch 1/3:   0%|          | 2/409 [00:23<1:18:33, 11.58s/it, loss=22]

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

Epoch 1/3:   1%|          | 3/409 [00:31<1:08:57, 10.19s/it, loss=15.3]

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

Epoch 1/3:   1%|          | 4/409 [00:39<1:02:00,  9.19s/it, loss=10.7]

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

Epoch 1/3:   1%|          | 5/409 [00:47<59:33,  8.85s/it, loss=21.4]

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

Epoch 1/3:   1%|▏         | 6/409 [00:58<1:04:30,  9.60s/it, loss=178]

torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])

KeyboardInterrupt:

In [ ]:
import torch
# Dataloader

# Model setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PatentEmbeddingModel(device=device, model_name="bert-base-uncased", freeze_encoder=True).to(device)
from tqdm import tqdm  # Install with: pip install tqdm

def train_model(model, device, dataloader, epochs=3, lr=1e-4, fine_tune=False):
    if fine_tune:
        for param in model.encoder.parameters():
            param.requires_grad = True

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    criterion = nn.MSELoss()
    model.train()

    for epoch in range(epochs):
        total_loss = 0
        # Wrap dataloader with tqdm
        progress_bar = tqdm(dataloader, desc=f"Epoch {epoch+1}/{epochs}", leave=False)
        for batch in progress_bar:
            optimizer.zero_grad()
            outputs = model(
                title=batch["title"],
                abstract=batch["abstract"],
                claims=batch["claims"],
                description=batch["description"]
            ).squeeze()
            loss = criterion(outputs, batch["label"].to(device))
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            # Update progress bar description
            progress_bar.set_postfix(loss=loss.item())
        
        epoch_loss = total_loss / len(dataloader)
        print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}")

train_model(model, device, dataloader, epochs=3, fine_tune=False)
train_model(model,device, dataloader, epochs=3, fine_tune=True)  # Fine-tune encoder

In [ ]:
from torch.utils.data import DataLoader

# Dataloader
dataloader = DataLoader(dataset, batch_size=8, shuffle=True)

# Model setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PatentEmbeddingModel("bert-base-uncased", freeze_encoder=True).to(device)

# Training function
def train_model(model, dataset, epochs=3, lr=1e-4, fine_tune=False):
    if fine_tune:
        for param in model.encoder.parameters():
            param.requires_grad = True

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    criterion = nn.MSELoss()
    model.train()

    for epoch in range(epochs):
        total_loss = 0
        for batch in dataloader:
            optimizer.zero_grad()

            inputs = {k: v for k, v in batch.items()}
            outputs = model(**inputs).squeeze()

            loss = criterion(outputs, batch["label"].to(device))
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss / len(dataloader)}")

train_model(model, dataloader, epochs=3, fine_tune=False)
train_model(model, dataloader, epochs=3, fine_tune=True)  # Fine-tune encoder

In [5]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [6]:

# from transformers import AutoTokenizer, AutoModel

# # Load PatentSBERTa
# tokenizer = AutoTokenizer.from_pretrained('AI-Growth-Lab/PatentSBERTa')
# model = AutoModel.from_pretrained('AI-Growth-Lab/PatentSBERTa')
# model.to(device)

# model.eval()  # Evaluation mode

In [7]:
# def mean_pooling(model_output, attention_mask):
#     token_embeddings = model_output.last_hidden_state  # [batch_size, seq_len, hidden_size]
#     input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size())
#     return (token_embeddings * input_mask_expanded).sum(1) / input_mask_expanded.sum(1)

# def chunk_text(text, max_words=300):
#     words = text.split()
#     return [' '.join(words[i:i+max_words]) for i in range(0, len(words), max_words)]

# def get_patent_embedding(text, batch_size=32):
#     chunks = chunk_text(text)
#     if not chunks:
#         return None

#     embeddings = []

#     for i in range(0, len(chunks), batch_size):
#         batch_chunks = chunks[i:i + batch_size]
#         inputs = tokenizer(batch_chunks, return_tensors='pt', truncation=True,
#                            padding=True, max_length=512)
#         inputs = {k: v.to(device) for k, v in inputs.items()}

#         with torch.no_grad():
#             outputs = model(**inputs)

#         pooled = mean_pooling(outputs, inputs['attention_mask'])  # Shape: [batch_size, hidden_size]
#         embeddings.append(pooled.cpu())

#     # Concatenate all batch embeddings, then average over all chunks
#     all_embeddings = torch.cat(embeddings, dim=0)  # Shape: [num_chunks, hidden_size]
#     return all_embeddings.mean(dim=0).numpy()

# def get_embedding_batched(text, batch_size=8):
#     chunks = chunk_text(text)
#     if not chunks:
#         return None
    
#     cls_embeddings = []
    
#     for i in range(0, len(chunks), batch_size):
#         batch_chunks = chunks[i:i + batch_size]
#         inputs = tokenizer(batch_chunks, return_tensors='pt', truncation=True,
#                            padding=True, max_length=512)
#         inputs = {k: v.to(device) for k, v in inputs.items()}

#         with torch.no_grad():
#             outputs = model(**inputs)
        
#         # CLS token is at position 0 for each sequence
#         cls_batch = outputs.last_hidden_state[:, 0, :]  # shape: (batch_size, hidden_dim)
#         cls_embeddings.append(cls_batch)
    
#     # Combine all CLS embeddings and mean-pool over them
#     all_cls = torch.cat(cls_embeddings, dim=0)  # (n_chunks, hidden_dim)
#     return all_cls.mean(dim=0).cpu().numpy()

In [8]:
# data["claims_embedding"] = data["claims_localized"].apply(get_patent_embedding)
# print("finished claims")
# data["title_embedding"] = data["title_localized"].apply(get_patent_embedding)
# print("finished titles")
# data["abstract_embedding"] = data["abstract_localized"].apply(get_patent_embedding)
# print("finished abstract")
# data["description_embedding"] = data["description_localized"].apply(get_patent_embedding)

In [9]:
# print(data["title_embedding"].apply(lambda x: None if x is None else x.shape).value_counts())
# print(data["abstract_embedding"].apply(lambda x: None if x is None else x.shape).value_counts())
# print(data["claims_embedding"].apply(lambda x: None if x is None else x.shape).value_counts())
# print(data["description_embedding"].apply(lambda x: None if x is None else x.shape).value_counts())